"""empty message

Revision ID: 33edd2375692
Revises: f5b3e958d62b
Create Date: 2024-02-02 10:34:13.717179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33edd2375692'
down_revision = 'f5b3e958d62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
